mostGoals1: 'nobody'
mostGoals2: 'nobody'
mostGoals3: 'nobody'
mostWins1: 'nobody'
mostWins2: 'nobody'
mostWins3: 'nobody'
longestStreak1: 'nobody'
longestStreak2: 'nobody'
longestStreak3: 'nobody'
mostAssists1: 'nobody'
mostAssists2: 'nobody'
mostAssists3: 'nobody'