name: qFootcube
version: '${project.version}'
main: me.qajic.plugins.qfootcube.Footcube
authors: [ qajic ]
description: Minecraft Soccer Plugin
api-version: 1.8
depend:
  - TitleAPI
commands:
  cube:
    description: spawns a ball, eh... cube
  clearCubes:
    description: removes all cubes
  clearCube:
    description: removes nearest cube
  tc:
    description: team-chat
  footcube:
    aliases: [fc]
    description: main plugin command
  commandDisabler:
    aliases: [cd]
    description: enable / disable commands in a match
  reload:
    description: Reloads messages config
  1v1:
    description: join 1v1
  2v2:
    description: join 2v2
  3v3:
    description: join 3v3
  4v4:
    description: join 4v4
  5v5:
    description: join 5v5
  abjuz:
    description: ne pitaj